### ISSUE TITLE
[Bug] 2FA breaks input

### ISSUE THREAD

**Issue by RiskiVR** [MintLily/BSLegacyUtil#1]
When steam info is entered, it sends a 2FA response if you have steam guard. However, it sends in the input field, so it's still expecting a version number. So if you were to try to enter it, it would just tell you "invalid input"

**Comment by MintLily** [comment]
Fixed - [023b4b3](https://github.com/KortyBoi/BSLegacyUtil/commit/023b4b30c2b0d4d48fe2b0629b457dbc707752ea)
