### ISSUE TITLE
Says newer version is available and crashes

### ISSUE THREAD

**Issue by mephist-0** [MintLily/BSLegacyUtil#10]
When launching the program it states a newer version is available before throwing an error and crashing.
(the error:
Unhandled exception. System. Net. Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
at System. Net . Http . HttpResponseMessage . EnsureSuccessStatusCode()
at System. Net. Http.HttpCIient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken canceltationToken)
at BSLegacyUtiI. Program. args
)
It also opens the releases page of the defunct Github page of the project (https://github.com/BeatSaberLegacyGroup/BSLegacyUtil/releases)

**To Reproduce**
Launch the program

**Screenshots**
![Screenshot_1](https://github.com/MintLily/BSLegacyUtil/assets/100721235/922e2a74-1469-46c9-819d-7cb95409e19a)

**Desktop:**
 - OS: [Windows 11]

**Comment by chillyshackk** [comment]
Just logged in to file the same. Also on Windows 11.

**Comment by MintLily** [comment]
This issue has been resolved as of v2023.1.4 - https://github.com/MintLily/BSLegacyUtil/releases/tag/2023.1.4
Thanks for the report!

**Comment by chillyshackk** [comment]
Seems to be back now :)
