### ISSUE TITLE
Error while moving files.

### ISSUE THREAD

**Issue by smd-pls** [MintLily/BSLegacyUtil#3]
![image](https://user-images.githubusercontent.com/87920893/126902702-d226d62b-0af8-4439-8b28-97fb57d5e959.png)

I am getting this error. Please help.

**Comment by MintLily** [comment]
I am unable to reproduce this error on my end. But I just updated the utility that allows you to launch the game from within the utility. Moving the game into your steam install is no longer necessary.

**Comment by smd-pls** [comment]
@MintLily Thank you! I have been using the UI launcher.
