### ISSUE TITLE
Login running for ever

### ISSUE THREAD

**Issue by JessyCat92** [MintLily/BSLegacyUtil#5]
**Describe the bug**
For some reason, When I try to login after selecting version, it asks for 2FA - So I enter my code and click enter - after that I get a screen "Sign In" and showing loading icon... this screen runs now forever.... (click on back doesn't work and the X crashes the app)

**To Reproduce**
1. Select Version (1.18.3 in my case)
2. Enter Username and Password
3. Enter 2FA
4. Get endless loading screen

**Expected behavior**
Download starts

**Screenshots**
https://i.imgur.com/WzJBmMO.jpg

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I also looked for logs:
[Assembly-CSharp_12.16.2021-13.51_.txt](https://github.com/MintLily/BSLegacyUtil/files/7727460/Assembly-CSharp_12.16.2021-13.51_.txt)

**Comment by MintLily** [comment]
First off, wrong Utility GitHub. Second, this is a known issue. We don't know what causes it. You just have to wait for Riski to update the application; we'll notify you in the Discord once this happens.
