### ISSUE TITLE
The program exits when logging into steam without the .net packages installed

### ISSUE THREAD

**Issue by ManateeMan92** [MintLily/BSLegacyUtil#7]
I was walking a friend through backdating and he was having a lot of trouble with logging in, so I'm reporting on his behalf.

Every time after my friend inputted his password, the window would promptly close.
He is on Windows 10.

Installing the .net packages fixed the issue.

**Comment by MintLily** [comment]
Well yeah, there's a reason why I link them the written tutorials. .NET 6 should be contain in the exe, but the .NET 5 is completely needed (and could not pack multiple versions) for DepotDownloader.

**Comment by MintLily** [comment]
Install this for Depotdownloader [.NET Core v5.0.10+ Runtime](https://link.bslegacy.com/dotNET_5-0-10)
