### ISSUE TITLE
DepotDownloader fails to start

### ISSUE THREAD

**Issue by nobully-osu** [MintLily/BSLegacyUtil#8]
**Describe the bug**
There seems to be a typo in executing DepotDownloader or something similar, preventing it from being executed. 

**To Reproduce**
1. Pick the first option to download a verison.
2. Enter username and password (does not have to be correct)
3. When attempting to execute DepotDownloader, it fails. 

**Screenshots**
![BSLegacyUtil_EaGJ94SSRz](https://user-images.githubusercontent.com/30556038/202572750-0adecc24-608b-4c05-a3e9-6d2fe3ea5aef.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: 2.12.2

**Comment by MintLily** [comment]
I already see the issue, I forget to add a path character to the folder. Let's fix it. I'll let you know here once it is done and a new version is released.

**Comment by MintLily** [comment]
The issue should be fixed: https://github.com/MintLily/BSLegacyUtil/releases/tag/2.12.3
